# Go to Yahoo! Finances URL and scrape information from the "Statistics" tab

This Python script fetches financial statistics data from a Yahoo Finance page for a specific company, with the ticker symbol "MSFT" (Microsoft) in this example. However, any publicly traded company's ticker can be used. It uses the requests library to send an HTTP GET request to the specified URL, including a user-agent header to mimic a browser request. Upon receiving a successful response (status code 200), it uses BeautifulSoup to parse the HTML content and extract all tables on the page. For each table, it iterates through the rows and columns to retrieve the metric names and their corresponding values, storing these in a dictionary. These dictionaries are then converted into pandas DataFrames. All DataFrames are concatenated into a single DataFrame, result_df, which holds the combined financial statistics.

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import numpy as np

In [ ]:


# URL of the Yahoo Finance statistics page for a specific company
# Replace the ticker with whatever company you want to get data for
url = "https://finance.yahoo.com/quote/MSFT/key-statistics"

# Rate limit in seconds to respect the server's resources
RATE_LIMIT = 5

def get_statistics(url):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
    }

    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')

        # Find all the tables containing the data
        tables = soup.find_all('table')
        data_frames = []

        for table in tables:
            # Find all rows in the table
            rows = table.find_all('tr')
            data = {'Metric': [], 'Value': []}

            for row in rows:
                # Find all columns in each row
                cols = row.find_all('td')
                if len(cols) > 1:
                    metric = cols[0].text.strip()
                    value = cols[1].text.strip()
                    data['Metric'].append(metric)
                    data['Value'].append(value)

            # Create a DataFrame for the current table
            df = pd.DataFrame(data)
            data_frames.append(df)

        # Combine all DataFrames into one
        result_df = pd.concat(data_frames, ignore_index=True)
        return result_df
    else:
        print(f"Error: Unable to fetch data. Status code: {response.status_code}")
        return pd.DataFrame()

#Final data is stored in df_statistics

if __name__ == "__main__":
    df_statistics = get_statistics(url)
    print(df_statistics)
    time.sleep(RATE_LIMIT)  # Respect the rate limit

Save the resulting dataframe to a csv file:

In [ ]:
# output df_statistics to a csv

df_statistics.to_csv('statistics.csv')

# Get data from the financials tab in Yahoo! Finance

This next chunk of code is designed to fetch financial data for a publicly traded company that exists on Yahoo!. It begins by defining the URL. The script then extracts the ticker symbol from the URL by locating the substring between "/quote/" and the next "/". A function named get_financials is defined, which sends an HTTP GET request to the provided URL with a user-agent header to mimic a browser. If the request is successful (status code 200), the HTML content is parsed using BeautifulSoup. The script searches for table rows within div elements that match a specific class (assumed to be "D(tbr)"). It treats the first row as containing column headers and the remaining rows as data rows, extracting text from each div within the rows. These are compiled into lists, and a pandas DataFrame is created with the first column set as the index ("Breakdown"). If the request fails, an empty DataFrame is returned.

In [ ]:


url = "https://finance.yahoo.com/quote/GILD/financials"

# Extract ticker from URL
# The ticker is between "/quote/" and the next "/"
start = url.find("/quote/") + len("/quote/")
end = url.find("/", start)
ticker = url[start:end]


def get_financials(url):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
    }

    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')

        # Find the table. This requires correct selectors for the actual table.
        # Assuming the table rows are in 'div' with a specific class (update class as per actual HTML structure)
        table_rows = soup.find_all('div', class_='D(tbr)')

        # Assuming the first 'div' of each row contains the row header (label)
        # and the subsequent 'divs' contain the data.
        row_headers = [row.find('div').get_text() for row in table_rows]

        # Assuming the first row contains column headers
        column_headers = ['Breakdown'] + [header.get_text() for header in table_rows[0].find_all('div', recursive=False)][1:]

        # Extracting data starting from the second row, since the first row contains headers
        data = []
        for row in table_rows[1:]:  # Skip the header row
            cols = row.find_all('div', recursive=False)
            row_data = [col.get_text() for col in cols]
            data.append(row_data)

        # Create DataFrame
        df = pd.DataFrame(data, columns=column_headers)
        df.set_index('Breakdown', inplace=True)

        return df
    else:
        print("Failed to fetch the data")
        return pd.DataFrame()

if __name__ == "__main__":
    df_financials = get_financials(url)
    print(df_financials)

                                                           ttm  12/31/2023  \
Breakdown
Total Revenue                                       27,116,000  27,116,000
Cost of Revenue                                      6,498,000   6,498,000
Gross Profit                                        20,618,000  20,618,000
Operating Expense                                   11,808,000  11,808,000
Operating Income                                     8,810,000   8,810,000
Net Non Operating Interest Income Expense             -944,000    -944,000
Other Income Expense                                -1,007,000  -1,007,000
Pretax Income                                        6,859,000   6,859,000
Tax Provision                                        1,247,000   1,247,000
Net Income Common Stockholders                       5,665,000   5,665,000
Diluted NI Available to Com Stockholders             5,665,000   5,665,000
Basic EPS                                                 4.70        4.54
Diluted EPS                                               4.67        4.50
Basic Average Shares                                 1,250,500   1,248,000
Diluted Average Shares                               1,260,500   1,258,000
Total Operating Income as Reported                   7,605,000   7,605,000
Total Expenses                                      18,306,000  18,306,000
Net Income from Continuing & Discontinued Opera...   5,665,000   5,665,000
Normalized Income                                    6,650,690   6,650,690
Interest Expense                                       944,000     944,000
Net Interest Income                                   -944,000    -944,000
EBIT                                                 7,803,000   7,803,000
EBITDA                                              10,496,000  10,496,000
Reconciled Cost of Revenue                           6,498,000   6,498,000
Reconciled Depreciation                              2,693,000   2,693,000
Net Income from Continuing Operation Net Minori...   5,665,000   5,665,000
Total Unusual Items Excluding Goodwill              -1,205,000  -1,205,000
Total Unusual Items                                 -1,205,000  -1,205,000
Normalized EBITDA                                   11,701,000  11,701,000
Tax Rate for Calcs                                           0           0
Tax Effect of Unusual Items                           -219,310    -219,310

                                                    12/31/2022  12/31/2021  \
Breakdown
Total Revenue                                       27,281,000  27,305,000
Cost of Revenue                                      5,657,000   6,601,000
Gross Profit                                        21,624,000  20,704,000
Operating Expense                                   10,650,000   9,847,000
Operating Income                                    10,974,000  10,857,000
Net Non Operating Interest Income Expense             -935,000  -1,001,000
Other Income Expense                                -4,225,000  -1,578,000
Pretax Income                                        5,814,000   8,278,000
Tax Provision                                        1,248,000   2,077,000
Net Income Common Stockholders                       4,592,000   6,225,000
Diluted NI Available to Com Stockholders             4,592,000   6,225,000
Basic EPS                                                 3.66        4.96
Diluted EPS                                               3.64        4.93
Basic Average Shares                                 1,255,000   1,256,000
Diluted Average Shares                               1,262,000   1,262,000
Total Operating Income as Reported                   7,330,000   9,918,000
Total Expenses                                      16,307,000  16,448,000
Net Income from Continuing & Discontinued Opera...   4,592,000   6,225,000
Normalized Income                                    7,452,540   6,928,311
Interest Expense                                       935,000   1,001,000
Net Interest Income                                   -935,000  -1,001,000
EBIT                                                 6,749,000   9,279,000
EBITDA                                               8,852,000  11,329,000
Reconciled Cost of Revenue                           5,657,000   6,601,000
Reconciled Depreciation                              2,103,000   2,050,000
Net Income from Continuing Operation Net Minori...   4,592,000   6,225,000
Total Unusual Items Excluding Goodwill              -3,644,000    -939,000
Total Unusual Items                                 -3,644,000    -939,000
Normalized EBITDA                                   12,496,000  12,268,000
Tax Rate for Calcs                                           0           0
Tax Effect of Unusual Items                           -783,460    -235,689

                                                    12/31/2020
Breakdown
Total Revenue                                       24,689,000
Cost of Revenue                                      4,572,000
Gross Profit                                        20,117,000
Operating Expense                                   10,190,000
Operating Income                                     9,927,000
Net Non Operating Interest Income Expense             -984,000
Other Income Expense                                -7,274,000
Pretax Income                                        1,669,000
Tax Provision                                        1,580,000
Net Income Common Stockholders                         123,000
Diluted NI Available to Com Stockholders               123,000
Basic EPS                                                 0.10
Diluted EPS                                               0.10
Basic Average Shares                                 1,257,000
Diluted Average Shares                               1,263,000
Total Operating Income as Reported                   4,071,000
Total Expenses                                      14,762,000
Net Income from Continuing & Discontinued Opera...     123,000
Normalized Income                                    4,397,880
Interest Expense                                       984,000
Net Interest Income                                   -984,000
EBIT                                                 2,653,000
EBITDA                                               4,133,000
Reconciled Cost of Revenue                           4,572,000
Reconciled Depreciation                              1,480,000
Net Income from Continuing Operation Net Minori...     123,000
Total Unusual Items Excluding Goodwill              -5,856,000
Total Unusual Items                                 -5,856,000
Normalized EBITDA                                    9,989,000
Tax Rate for Calcs                                           0
Tax Effect of Unusual Items                         -1,581,120

# Cleaning the data

For each column in the DataFrame, this code removes dollar signs and commas, replaces cells containing only a dash with NaN, and attempts to convert the values to floats. The index name 'Breakdown' is removed for simplicity, and the index is reset to make 'Breakdown' a regular column. Additionally, a new column 'Ticker' is added to the DataFrame, containing the ticker symbol of the company. Finally, the updated DataFrame, which now includes NaN values where there were originally only dashes, is printed.

In [ ]:
# Convert all number-like strings to floats, remove commas, and replace only dashes with NaN
for column in df_financials.columns:
    df_financials[column] = (
        df_financials[column]
        .replace('[\$,]', '', regex=True)  # remove dollar signs and commas
        .replace('^\-$', np.nan, regex=True)  # replace cells with only a dash with NaN
        .astype(float, errors='ignore')  # convert to float, ignore if conversion is not possible
    )

# Remove the index name 'Breakdown' if not necessary
df_financials.index.name = None

# Reset the index if you want 'Breakdown' as a regular column
df_financials.reset_index(inplace=True)


#show ticker for company
df_financials['Ticker'] = ticker

# Now, 'df_financials' should have NaN where there were only dashes
print(df_financials)

                                                index          ttm  \
0                                       Total Revenue  27116000.00
1                                     Cost of Revenue   6498000.00
2                                        Gross Profit  20618000.00
3                                   Operating Expense  11808000.00
4                                    Operating Income   8810000.00
5           Net Non Operating Interest Income Expense   -944000.00
6                                Other Income Expense  -1007000.00
7                                       Pretax Income   6859000.00
8                                       Tax Provision   1247000.00
9                      Net Income Common Stockholders   5665000.00
10           Diluted NI Available to Com Stockholders   5665000.00
11                                          Basic EPS         4.70
12                                        Diluted EPS         4.67
13                               Basic Average Shares   1250500.00
14                             Diluted Average Shares   1260500.00
15                 Total Operating Income as Reported   7605000.00
16                                     Total Expenses  18306000.00
17  Net Income from Continuing & Discontinued Oper...   5665000.00
18                                  Normalized Income   6650690.00
19                                   Interest Expense    944000.00
20                                Net Interest Income   -944000.00
21                                               EBIT   7803000.00
22                                             EBITDA  10496000.00
23                         Reconciled Cost of Revenue   6498000.00
24                            Reconciled Depreciation   2693000.00
25  Net Income from Continuing Operation Net Minor...   5665000.00
26             Total Unusual Items Excluding Goodwill  -1205000.00
27                                Total Unusual Items  -1205000.00
28                                  Normalized EBITDA  11701000.00
29                                 Tax Rate for Calcs         0.00
30                        Tax Effect of Unusual Items   -219310.00

     12/31/2023   12/31/2022   12/31/2021  12/31/2020 Ticker
0   27116000.00  27281000.00  27305000.00  24689000.0   GILD
1    6498000.00   5657000.00   6601000.00   4572000.0   GILD
2   20618000.00  21624000.00  20704000.00  20117000.0   GILD
3   11808000.00  10650000.00   9847000.00  10190000.0   GILD
4    8810000.00  10974000.00  10857000.00   9927000.0   GILD
5    -944000.00   -935000.00  -1001000.00   -984000.0   GILD
6   -1007000.00  -4225000.00  -1578000.00  -7274000.0   GILD
7    6859000.00   5814000.00   8278000.00   1669000.0   GILD
8    1247000.00   1248000.00   2077000.00   1580000.0   GILD
9    5665000.00   4592000.00   6225000.00    123000.0   GILD
10   5665000.00   4592000.00   6225000.00    123000.0   GILD
11         4.54         3.66         4.96         0.1   GILD
12         4.50         3.64         4.93         0.1   GILD
13   1248000.00   1255000.00   1256000.00   1257000.0   GILD
14   1258000.00   1262000.00   1262000.00   1263000.0   GILD
15   7605000.00   7330000.00   9918000.00   4071000.0   GILD
16  18306000.00  16307000.00  16448000.00  14762000.0   GILD
17   5665000.00   4592000.00   6225000.00    123000.0   GILD
18   6650690.00   7452540.00   6928311.00   4397880.0   GILD
19    944000.00    935000.00   1001000.00    984000.0   GILD
20   -944000.00   -935000.00  -1001000.00   -984000.0   GILD
21   7803000.00   6749000.00   9279000.00   2653000.0   GILD
22  10496000.00   8852000.00  11329000.00   4133000.0   GILD
23   6498000.00   5657000.00   6601000.00   4572000.0   GILD
24   2693000.00   2103000.00   2050000.00   1480000.0   GILD
25   5665000.00   4592000.00   6225000.00    123000.0   GILD
26  -1205000.00  -3644000.00   -939000.00  -5856000.0   GILD
27  -1205000.00  -3644000.00   -939000.00  -5856000.0   GILD
28  11701000.00  12496000.00  12268000.00   9989000.0   GILD
29         0.00         0.00         0.00         0.0   GILD
30   -219310.00   -783460.00   -235689.00  -1581120.0   GILD

In [ ]:
#write df_financials to a csv

df_financials.to_csv('financials.csv')
df_financials

,index,ttm,12/31/2023,12/31/2022,12/31/2021,12/31/2020,Ticker
0,Total Revenue,27116000.00,27116000.00,27281000.00,27305000.00,24689000.0,GILD
1,Cost of Revenue,6498000.00,6498000.00,5657000.00,6601000.00,4572000.0,GILD
2,Gross Profit,20618000.00,20618000.00,21624000.00,20704000.00,20117000.0,GILD
3,Operating Expense,11808000.00,11808000.00,10650000.00,9847000.00,10190000.0,GILD
4,Operating Income,8810000.00,8810000.00,10974000.00,10857000.00,9927000.0,GILD
5,Net Non Operating Interest Income Expense,-944000.00,-944000.00,-935000.00,-1001000.00,-984000.0,GILD
6,Other Income Expense,-1007000.00,-1007000.00,-4225000.00,-1578000.00,-7274000.0,GILD
7,Pretax Income,6859000.00,6859000.00,5814000.00,8278000.00,1669000.0,GILD
8,Tax Provision,1247000.00,1247000.00,1248000.00,2077000.00,1580000.0,GILD
9,Net Income Common Stockholders,5665000.00,5665000.00,4592000.00,6225000.00,123000.0,GILD
10,Diluted NI Available to Com Stockholders,5665000.00,5665000.00,4592000.00,6225000.00,123000.0,GILD
11,Basic EPS,4.70,4.54,3.66,4.96,0.1,GILD
12,Diluted EPS,4.67,4.50,3.64,4.93,0.1,GILD
13,Basic Average Shares,1250500.00,1248000.00,1255000.00,1256000.00,1257000.0,GILD
14,Diluted Average Shares,1260500.00,1258000.00,1262000.00,1262000.00,1263000.0,GILD
15,Total Operating Income as Reported,7605000.00,7605000.00,7330000.00,9918000.00,4071000.0,GILD
16,Total Expenses,18306000.00,18306000.00,16307000.00,16448000.00,14762000.0,GILD
17,Net Income from Continuing & Discontinued Oper...,5665000.00,5665000.00,4592000.00,6225000.00,123000.0,GILD
18,Normalized Income,6650690.00,6650690.00,7452540.00,6928311.00,4397880.0,GILD
19,Interest Expense,944000.00,944000.00,935000.00,1001000.00,984000.0,GILD
20,Net Interest Income,-944000.00,-944000.00,-935000.00,-1001000.00,-984000.0,GILD
21,EBIT,7803000.00,7803000.00,6749000.00,9279000.00,2653000.0,GILD
22,EBITDA,10496000.00,10496000.00,8852000.00,11329000.00,4133000.0,GILD
23,Reconciled Cost of Revenue,6498000.00,6498000.00,5657000.00,6601000.00,4572000.0,GILD
24,Reconciled Depreciation,2693000.00,2693000.00,2103000.00,2050000.00,1480000.0,GILD
25,Net Income from Continuing Operation Net Minor...,5665000.00,5665000.00,4592000.00,6225000.00,123000.0,GILD
26,Total Unusual Items Excluding Goodwill,-1205000.00,-1205000.00,-3644000.00,-939000.00,-5856000.0,GILD
27,Total Unusual Items,-1205000.00,-1205000.00,-3644000.00,-939000.00,-5856000.0,GILD
28,Normalized EBITDA,11701000.00,11701000.00,12496000.00,12268000.00,9989000.0,GILD
29,Tax Rate for Calcs,0.00,0.00,0.00,0.00,0.0,GILD
30,Tax Effect of Unusual Items,-219310.00,-219310.00,-783460.00,-235689.00,-1581120.0,GILD

# Final Consolidated Code

I decided to consolidate the code into one code block for convenience purposes, as this was what my teammates and project supervisor wanted.

In [ ]:

def get_soup(url):
    """Fetch the HTML content from a URL and return a BeautifulSoup object."""
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
    }
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        return BeautifulSoup(response.text, 'html.parser')
    else:
        print(f"Failed to fetch the data. Status code: {response.status_code}")
        return None

def get_statistics(soup):
    """Extract statistics data from the BeautifulSoup object and return a DataFrame."""
    tables = soup.find_all('table')
    data_frames = []
    for table in tables:
        rows = table.find_all('tr')
        data = {'Metric': [], 'Value': []}
        for row in rows:
            cols = row.find_all('td')
            if len(cols) > 1:
                metric = cols[0].text.strip()
                value = cols[1].text.strip()
                data['Metric'].append(metric)
                data['Value'].append(value)
        df = pd.DataFrame(data)
        data_frames.append(df)
    return pd.concat(data_frames, ignore_index=True) if data_frames else pd.DataFrame()

def get_financials(soup):
    """Extract financials data from the BeautifulSoup object and return a DataFrame."""
    table_rows = soup.find_all('div', class_='D(tbr)')
    if not table_rows:
        return pd.DataFrame()
    column_headers = ['Breakdown'] + [header.get_text() for header in table_rows[0].find_all('div', recursive=False)][1:]
    data = [[col.get_text() for col in row.find_all('div', recursive=False)] for row in table_rows[1:]]
    df = pd.DataFrame(data, columns=column_headers)
    df.set_index('Breakdown', inplace=True)
    return df

def clean_and_augment_financials(df_financials, ticker):
    """Clean and augment the financials DataFrame."""
    for column in df_financials.columns:
        df_financials[column] = (
            df_financials[column]
            .replace('[\$,]', '', regex=True)
            .replace('^\-$', np.nan, regex=True)
            .astype(float, errors='ignore')
        )
    df_financials.index.name = None
    df_financials.reset_index(inplace=True)
    df_financials['Ticker'] = ticker
    return df_financials

if __name__ == "__main__":
    # Prompt user for a ticker symbol
    ticker = input("Enter the ticker symbol of the company: ").strip().upper()

    # Construct URLs
    statistics_url = f"https://finance.yahoo.com/quote/{ticker}/key-statistics"
    financials_url = f"https://finance.yahoo.com/quote/{ticker}/financials"

    # Fetch and print statistics
    soup_statistics = get_soup(statistics_url)
    if soup_statistics:
        df_statistics = get_statistics(soup_statistics)
        print("\nStatistics DataFrame:")
        print(df_statistics)

    # Fetch, clean, and print financials
    soup_financials = get_soup(financials_url)
    if soup_financials:
        df_financials = get_financials(soup_financials)
        df_financials = clean_and_augment_financials(df_financials, ticker)
        print("\nFinancials DataFrame:")
        print(df_financials)

Enter the ticker symbol of the company: GILD

Statistics DataFrame:
                                            Metric         Value
0                            Market Cap (intraday)        92.16B
1                                 Enterprise Value       109.89B
2                                     Trailing P/E         16.44
3                                      Forward P/E         10.48
4                        PEG Ratio (5 yr expected)          0.46
5                                Price/Sales (ttm)          3.43
6                                 Price/Book (mrq)          4.04
7                         Enterprise Value/Revenue          4.05
8                          Enterprise Value/EBITDA         10.47
9                                Beta (5Y Monthly)          0.20
10                                52-Week Change 3        -6.07%
11                         S&P500 52-Week Change 3        32.31%
12                                  52 Week High 3         87.87
13                                   52 Week Low 3         71.37
14                         50-Day Moving Average 3         76.70
15                        200-Day Moving Average 3         77.37
16                             Avg Vol (3 month) 3         7.35M
17                              Avg Vol (10 day) 3         8.52M
18                            Shares Outstanding 5         1.25B
19                    Implied Shares Outstanding 6         1.25B
20                                         Float 8         1.24B
21                            % Held by Insiders 1         0.10%
22                        % Held by Institutions 1        88.53%
23                   Shares Short (Feb 29, 2024) 4        19.67M
24                    Short Ratio (Feb 29, 2024) 4          2.55
25               Short % of Float (Feb 29, 2024) 4         1.77%
26  Short % of Shares Outstanding (Feb 29, 2024) 4         1.58%
27       Shares Short (prior month Jan 31, 2024) 4        15.66M
28                  Forward Annual Dividend Rate 4          3.08
29                 Forward Annual Dividend Yield 4         4.16%
30                 Trailing Annual Dividend Rate 3          3.00
31                Trailing Annual Dividend Yield 3         4.06%
32                 5 Year Average Dividend Yield 4          3.97
33                                  Payout Ratio 4        66.67%
34                                 Dividend Date 3  Mar 28, 2024
35                              Ex-Dividend Date 4  Mar 14, 2024
36                             Last Split Factor 2           2:1
37                               Last Split Date 3  Jan 28, 2013
38                                Fiscal Year Ends  Dec 31, 2023
39                       Most Recent Quarter (mrq)  Dec 31, 2023
40                                   Profit Margin        20.89%
41                          Operating Margin (ttm)        42.21%
42                          Return on Assets (ttm)         9.78%
43                          Return on Equity (ttm)        25.54%
44                                   Revenue (ttm)        27.12B
45                         Revenue Per Share (ttm)         21.73
46                  Quarterly Revenue Growth (yoy)        -3.70%
47                              Gross Profit (ttm)           N/A
48                                          EBITDA        12.49B
49                  Net Income Avi to Common (ttm)         5.66B
50                               Diluted EPS (ttm)          4.50
51                 Quarterly Earnings Growth (yoy)       -12.90%
52                                Total Cash (mrq)         8.35B
53                      Total Cash Per Share (mrq)           6.7
54                                Total Debt (mrq)        25.66B
55                         Total Debt/Equity (mrq)       112.79%
56                             Current Ratio (mrq)          1.43
57                      Book Value Per Share (mrq)         18.33
58                       Operating Cash Flow (ttm)         8.01B
59                    Levered Free Cash Flow (ttm)         8.79B

Financials DataFrame:
                                                index          ttm  \
0                                       Total Revenue  27116000.00
1                                     Cost of Revenue   6498000.00
2                                        Gross Profit  20618000.00
3                                   Operating Expense  11808000.00
4                                    Operating Income   8810000.00
5           Net Non Operating Interest Income Expense   -944000.00
6                                Other Income Expense  -1007000.00
7                                       Pretax Income   6859000.00
8                                       Tax Provision   1247000.00
9                      Net Income Common Stockholders   5665000.00
10           Diluted NI Available to Com Stockholders   5665000.00
11                                          Basic EPS         4.70
12                                        Diluted EPS         4.67
13                               Basic Average Shares   1250500.00
14                             Diluted Average Shares   1260500.00
15                 Total Operating Income as Reported   7605000.00
16                                     Total Expenses  18306000.00
17  Net Income from Continuing & Discontinued Oper...   5665000.00
18                                  Normalized Income   6650690.00
19                                   Interest Expense    944000.00
20                                Net Interest Income   -944000.00
21                                               EBIT   7803000.00
22                                             EBITDA  10496000.00
23                         Reconciled Cost of Revenue   6498000.00
24                            Reconciled Depreciation   2693000.00
25  Net Income from Continuing Operation Net Minor...   5665000.00
26             Total Unusual Items Excluding Goodwill  -1205000.00
27                                Total Unusual Items  -1205000.00
28                                  Normalized EBITDA  11701000.00
29                                 Tax Rate for Calcs         0.00
30                        Tax Effect of Unusual Items   -219310.00

     12/31/2023   12/31/2022   12/31/2021  12/31/2020 Ticker
0   27116000.00  27281000.00  27305000.00  24689000.0   GILD
1    6498000.00   5657000.00   6601000.00   4572000.0   GILD
2   20618000.00  21624000.00  20704000.00  20117000.0   GILD
3   11808000.00  10650000.00   9847000.00  10190000.0   GILD
4    8810000.00  10974000.00  10857000.00   9927000.0   GILD
5    -944000.00   -935000.00  -1001000.00   -984000.0   GILD
6   -1007000.00  -4225000.00  -1578000.00  -7274000.0   GILD
7    6859000.00   5814000.00   8278000.00   1669000.0   GILD
8    1247000.00   1248000.00   2077000.00   1580000.0   GILD
9    5665000.00   4592000.00   6225000.00    123000.0   GILD
10   5665000.00   4592000.00   6225000.00    123000.0   GILD
11         4.54         3.66         4.96         0.1   GILD
12         4.50         3.64         4.93         0.1   GILD
13   1248000.00   1255000.00   1256000.00   1257000.0   GILD
14   1258000.00   1262000.00   1262000.00   1263000.0   GILD
15   7605000.00   7330000.00   9918000.00   4071000.0   GILD
16  18306000.00  16307000.00  16448000.00  14762000.0   GILD
17   5665000.00   4592000.00   6225000.00    123000.0   GILD
18   6650690.00   7452540.00   6928311.00   4397880.0   GILD
19    944000.00    935000.00   1001000.00    984000.0   GILD
20   -944000.00   -935000.00  -1001000.00   -984000.0   GILD
21   7803000.00   6749000.00   9279000.00   2653000.0   GILD
22  10496000.00   8852000.00  11329000.00   4133000.0   GILD
23   6498000.00   5657000.00   6601000.00   4572000.0   GILD
24   2693000.00   2103000.00   2050000.00   1480000.0   GILD
25   5665000.00   4592000.00   6225000.00    123000.0   GILD
26  -1205000.00  -3644000.00   -939000.00  -5856000.0   GILD
27  -1205000.00  -3644000.00   -939000.00  -5856000.0   GILD
28  11701000.00  12496000.00  12268000.00   9989000.0   GILD
29         0.00         0.00         0.00         0.0   GILD
30   -219310.00   -783460.00   -235689.00  -1581120.0   GILD